### ISSUE TITLE
Redundant title tag for some icons

### ISSUE THREAD

**Issue by ruud-altenburg** [zostera/django-icons#16]
Some icons have ```__title__``` as title. I could not find a way to disable the creation of a title tag, or a way to add a relevant one in a template.

<img width="335" alt="Screenshot 2020-03-17 at 14 47 07" src="https://user-images.githubusercontent.com/7580450/76862435-66da0480-685e-11ea-8545-a727ce21bfeb.png">

**Comment by dyve** [comment]
The string `__title__` does not occur in this codebase. It it something specific to an implementation. I'll look into that.
