### ISSUE TITLE
Allow getting the html for an icon in regular python.

### ISSUE THREAD

**Issue by jieter** [zostera/django-icons#2]
Sometimes I want to use an icon in regular python code, for example in a django-tables2 table.

I can do something like this:
```python
from django_icons.utils import get_icon_kwargs_from_settings

format_html('<i class="{}"></i>', get_icon_kwargs_from_settings('info')['name'])
```

But it would be nice if django-icons would expose something like this:
```python
>>> from django_icons import icon
>>> icon('info')
'<i class="far fa-info-circle"></i>'
```

**Comment by dyve** [comment]
Fixed in #13e79ea41b531819278c6ce9877f88382b7a379b
