### ISSUE TITLE
django-icons not supporting stacked icons?

### ISSUE THREAD

**Issue by bschollnick** [zostera/django-icons#34]
The one caveat here is that I'm using jinja2, so I'm using:

from django_icons.templatetags.icons import icon

So

```{% icon 'pencil' %}```
is actually 
```{{ icon("pencil") }}```
with my setup.

I'd like to use the font-awesome feature for stacking FA characters over each other... But I can't seem to get it to work.
(eg. https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons)

```
<span class="fa-stack fa-2x">
  <i class="fas fa-square fa-stack-2x"></i>
  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
</span> 
```

and trying the examples as written just ends up with a black 2x square.  

Digging into this...

{{ icon('square fa-stack-2x') }}
Produces:
```

>>> icon('square fa-stack-2x')
'<i class="fa fa-square fa-stack-2x"></i>'

compare that to

  <i class="fas fa-square fa-stack-2x"></i>
```

So I suspect  fa != fas (font-awesome-stack?) in the class produced by django-icons?

```

>>> icon('twitter fa-stack-2x fa-inverse')
'<i class="fa fa-twitter fa-stack-2x fa-inverse"></i>'
compare that to:
  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
```
so fa != fab?  (Font-awesome-base?)

Can you confirm if Django-icons support stacking at this point?  I strongly suspect not.

**Comment by dyve** [comment]
Hi there, thanks for reporting this.

I suspect you are using the FontAwesome renderer. This is meant for FontAwesome 4, which only had the `fa` prefix. I think we can document this better.

For FontAwesome 5 and above, use the BaseRenderer and specify the exact classes, like this (in settings.py):

```python
# Settings for django-icons
DJANGO_ICONS = {
    "DEFAULTS": {"renderer": "BaseRenderer"},
    "ICONS": {
        "warning": {"name": "fas fa-exclamation-triangle"},
}
```

Or in a Django template (assuming `BaserRenderer`):

```django
{% load icons %}
{% icon "fas fa-exclamation-triangle" %}
```

For stacked icons, you'd need a specific renderer that outputs the wqrapper and the individual icons. or build the stacked icon like this in your template:

```django
{% load icons %}
<span class="fa-stack fa-2x">
  {% icon "fas fa-square fa-stack-2x" %}
  {% icon "fab fa-twitter fa-stack-1x fa-inverse" %}
</span>
```

In this example, using `django-icons` isn't much better than just writing the HTML yourself. The power of this library is mainly in settings default icons and classes. For example, if all your icons need the `aria-hidden` attribute, you could set

```python
# Settings for django-icons
DJANGO_ICONS = {
    "DEFAULTS": {"renderer": "BaseRenderer", "attrs": {"aria-hidden": True}},
    # ...
}
```

**Comment by dyve** [comment]
Just writing down an idea revisiting this. We might allow stacked or multi icons with a wrapper. It would be cool to be able to predefine a stacked icon and re-use it. We would have to deal with where the extra classes went (probably the wrapper, or add an indicator of depth / target of extra classes.
