### ISSUE TITLE
[Getting ERROR] - 'icons' is not a registered tag library. Must be one of

### ISSUE THREAD

**Issue by swastkk** [zostera/django-icons#354]
Getting this error `'icons' is not a registered tag library. Must be one of:`
setting.py
```
DJANGO_ICONS = {
    "ICONS": {
        "icon": {"name": "ion-ios-locked-outline"},
    },
}
```
and in the template
```
 <div class="illustration">{% load icons %}{% icon 'icon' %}</div>
```
Followed each and every step mentioned in the https://pypi.org/project/django-icons/

**Comment by swastkk** [comment]
Solved this error by adding `django_icons` but need to add this in the documentation of the project because it can cause problems to many other newbies out there.

**Comment by dyve** [comment]
You mean adding `django_icons` to `INSTALLED_APPS`?

**Comment by swastkk** [comment]
> You mean adding `django_icons` to `INSTALLED_APPS`?

Yess
