### ISSUE TITLE
django_icons never renders the icons in html pages

### ISSUE THREAD

**Issue by swastkk** [zostera/django-icons#392]
This was my 3rd Try but still  it is not showing up the `icons` followed each and every step which is being mentioned, 
in the inspect element of browser, it is showing up the code for the icon, but cana't see the ICON on the  main html page.
<p>
<img src="https://github.com/zostera/django-icons/assets/81990329/4cbb57d5-da4a-47c0-88af-01b6fc424293" width="40%">
<img src="https://github.com/zostera/django-icons/assets/81990329/ab3a8c6f-ac81-474d-ac55-72525fe562b1" width="50%">
</p>

![image](https://github.com/zostera/django-icons/assets/81990329/3990c588-4549-4641-9d14-104f39ede72d)
Please help as I need to submit this work asap.

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-icons`, we'll be happy to reply over there!

As a start, you could share your full code there. When displaying icons, you should also include the relevant icon library (for example, FontAwesome).
