### ISSUE TITLE
Icon not rendered in html

### ISSUE THREAD

**Issue by ImanoWilliams** [zostera/django-icons#5]
{% load icons %}

{% block content %}
<p>
        {% icon 'user' %}
        The `user` icon from FontAwesome
</p>

{% endblock %}

**Comment by dyve** [comment]
HI, can you share the generated HTML?

**Comment by ImanoWilliams** [comment]
In my settings.py
# code
INSTALLED_APPS = [
....,
'django_icons',....]

Html file


{% extends 'articles/articles_base.html' %}

{% load icons %}

{% block container %}
  <h3 class="title"> {% icon 'th-list' %} List of Articles</h3>
  <div class="collection">
    {% for article in article_list %}
        <a class="collection-item" href="{% url 'article-detail' article.id %}">{{article.title}}</a>
    {% endfor %}
  </div>
  <a class="btn right" href="{% url 'article-create' %}">Create Article</a>
{% endblock %}

**Comment by dyve** [comment]
This is your template file, not the generated HTML (you can see that with View Source in your browser). I think you did not include Font Awesome in your templates. To be sure, ask this question on StackOverflow.com, link this ticket, and I'm sure you'll get an answer there.

**Comment by ImanoWilliams** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Class Based Views Rock</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <style>
      .title {
        text-align: center;
        font-weight: 200;
      }
    </style>
  </head>
  <body>
    
      <div class="container">
        
  <h3 class="title"> <i class="fa fa-shield"></i>All Articles</h3>
  <div class="collection">
    
        <a class="collection-item" href="/blog/1/">rr</a>
    
        <a class="collection-item" href="/blog/2/">gg</a>
    
  </div>
  <a class="btn right" href="/blog/create/">Create Article</a>

      </div>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js" />
  </body>
</html>

**Comment by ImanoWilliams** [comment]
OK. Thanks. 
I am new to Django and how these packages work when loaded into a django project. 
I want to use django-bootstrap4 along with django_icons and my custom css files for a project, but I do not understand how they all fit together.

**Comment by dyve** [comment]
@ImanoWilliams StackOverflow.com is your friend then!
