### ISSUE TITLE
version 4.0.0 does not work

### ISSUE THREAD

**Issue by catborise** [zostera/django-icons#65]
Hi,
we are using django-icons 3.0.0 without any problem but if we update it to 4.0.0 icons does not seen.
documents do not contain any info with migrate.
is there a major change?

thanks

```
requirements.txt
django-icons==4.0.0

settings.conf
INSTALLED_APPS = [
....
"bootstrap4",
"django_icons",
...
]

html page:
{% load icons %}
<a class="btn btn-sm btn-secondary disabled" title="{% trans "Suspend" %}">{% icon 'pause' %}</a>
```
in that example, icon empty.

**Comment by dyve** [comment]
Hi, thanks for reaching out. In the CHANGELOG:

> Set IconRenderer as default renderer (#58).

Your pause icon would be rendered as FontAwesome4 `<i class="fa fa-pause"></i>' in 3.0.0.

In 4.0.0, it would render as just the pause class `<i class="pause"></i>'.

To fix this, you can set the FontAwesome4Renderer as default, and/or explicitly define icons in your settings. See https://django-icons.readthedocs.io/en/latest/settings.html
