### ISSUE TITLE
font-awesome 5 moves brand icons to fab class, breaking {% icon "facebook" %} and others

### ISSUE THREAD

**Issue by wamcvey** [zostera/django-icons#9]
using {% icon "facebook"} builds HTML that looks like: 
`<i class="fa fa-facebook">`
but font awesome5 has moved icons associated with brands into being rendered based on the `.fab` class definition: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
Even trying to manually enter in the class with by passing in `extra_classes="fab"` to `icon` tag fails because of apparent ordering issues. It'd be great if {% icon %} could know when to use the `fab` class attr vs the standard `fa` attr.

**Comment by dyve** [comment]
Thanks, we'll look into this. This works for our projects (as a workaround?):

```
    "ICONS": {
        "facebook": {"name": "fab fa-facebook"},
    }
```

**Comment by dyve** [comment]
We've adopted the workaround. FA5 works brilliantly without a special rendering class.
